import { site } from "@/content/site";

/**
 * DigiDan isometric block mark — three separable pieces (teal foundation,
 * amber tower, coral cube). Geometry generated by scripts/generate-logo.mjs.
 * Each piece is a <g data-piece> so Phase 3 can animate the assembly.
 * Flat fills, three-face convention, no gradients (brand rules 3.1 / 3.4).
 */

type Piece = {
  name: "teal" | "amber" | "coral";
  left: string; // dark face
  right: string; // mid face
  top: string; // light face
  fills: { dark: string; mid: string; light: string };
};

const PIECES: Piece[] = [
  {
    name: "teal",
    left: "-68,34 0,68 0,34 -68,0",
    right: "68,34 0,68 0,34 68,0",
    top: "0,-34 68,0 0,34 -68,0",
    fills: { dark: "#147A5A", mid: "#1D9E75", light: "#5DCAA5" },
  },
  {
    name: "amber",
    left: "0,0 34,17 34,-51 0,-68",
    right: "68,0 34,17 34,-51 68,-68",
    top: "34,-85 68,-68 34,-51 0,-68",
    fills: { dark: "#C67C10", mid: "#EF9F27", light: "#FAC775" },
  },
  {
    name: "coral",
    left: "-68,0 -34,17 -34,-17 -68,-34",
    right: "0,0 -34,17 -34,-17 0,-34",
    top: "-34,-51 0,-34 -34,-17 -68,-34",
    fills: { dark: "#A8431F", mid: "#D85A30", light: "#F0997B" },
  },
];

export function LogoMark({
  size = 40,
  className,
  title = "DigiDan",
}: {
  size?: number;
  className?: string;
  title?: string;
}) {
  return (
    <svg
      viewBox="-74 -91 148 165"
      width={size}
      height={(size * 165) / 148}
      className={className}
      role="img"
      aria-label={title}
    >
      {PIECES.map((p) => (
        <g key={p.name} data-piece={p.name}>
          <polygon points={p.left} fill={p.fills.dark} />
          <polygon points={p.right} fill={p.fills.mid} />
          <polygon points={p.top} fill={p.fills.light} />
        </g>
      ))}
    </svg>
  );
}

export function Wordmark({ className }: { className?: string }) {
  return (
    <span
      className={className}
      style={{
        fontFamily: "var(--font-display)",
        fontWeight: 500,
        letterSpacing: "0.22em",
      }}
      aria-hidden="true"
    >
      {site.wordmark}
    </span>
  );
}

export function LogoLockup({ size = 34 }: { size?: number }) {
  return (
    <span className="inline-flex items-center gap-2.5">
      <LogoMark size={size} />
      <Wordmark className="text-[1.05rem] text-ink" />
      <span className="sr-only">{site.name}</span>
    </span>
  );
}
